

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."continents" AS ENUM (
    'Africa',
    'Antarctica',
    'Asia',
    'Europe',
    'Oceania',
    'North America',
    'South America'
);


ALTER TYPE "public"."continents" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_parent_tags_and_siblings"("tag_ids" bigint[]) RETURNS TABLE("id" bigint, "name" "text", "parent_id" smallint)
    LANGUAGE "sql"
    AS $$
WITH RECURSIVE
  parent_tags AS (
    SELECT
      id,
      NAME,
      parent_id
    FROM
      public.tags
    WHERE
      id = ANY (tag_ids) -- Replace with your list of integers
    UNION ALL
    SELECT
      t.id,
      t.name,
      t.parent_id
    FROM
      public.tags t
      INNER JOIN parent_tags pt ON t.id = pt.parent_id
  ),
  siblings AS (
    SELECT
      t.id,
      t.name,
      t.parent_id
    FROM
      public.tags t
      INNER JOIN parent_tags pt ON t.parent_id = pt.parent_id
    WHERE
      t.id <> pt.id -- Exclude the tag itself
  )
SELECT
  id,
  NAME,
  parent_id
FROM
  parent_tags
UNION
SELECT
  id,
  NAME,
  parent_id
FROM
  siblings;
$$;


ALTER FUNCTION "public"."get_parent_tags_and_siblings"("tag_ids" bigint[]) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_parent_tags_multiple"("tag_ids" bigint[]) RETURNS TABLE("id" bigint, "name" "text", "parent_id" smallint)
    LANGUAGE "sql"
    AS $$
WITH RECURSIVE parent_tags AS (
    SELECT 
        id,
        name,
        parent_id
    FROM 
        public.tags
    WHERE 
        id = ANY(tag_ids)  -- Start with the tags having the specified ids

    UNION ALL

    SELECT 
        t.id,
        t.name,
        t.parent_id
    FROM 
        public.tags t
    INNER JOIN 
        parent_tags pt ON t.id = pt.parent_id  -- Join to find parent tags
)
SELECT 
    id,
    name,
    parent_id
FROM 
    parent_tags;
$$;


ALTER FUNCTION "public"."get_parent_tags_multiple"("tag_ids" bigint[]) OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" smallint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "alternative_names" "text"[],
    "parent_id" smallint,
    "name" "text",
    "search_vector" "tsvector"
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."search_tags_by_prefix"("prefix" "text") RETURNS SETOF "public"."tags"
    LANGUAGE "plpgsql"
    AS $$
begin
  return query
  select * from tags where search_vector @@ to_tsquery(prefix || ':*');
end;
$$;


ALTER FUNCTION "public"."search_tags_by_prefix"("prefix" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."tags_search_vector_update"() RETURNS "trigger"
    LANGUAGE "plpgsql"
    AS $$BEGIN
    NEW.search_vector := to_tsvector(
        'english',
        coalesce(NEW.name, '') || ' ' || 
        coalesce(array_to_string(NEW.alternative_names, ' '), '')
    );
    RETURN NEW;
END;$$;


ALTER FUNCTION "public"."tags_search_vector_update"() OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."blob_tags" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "blob_id" bigint NOT NULL,
    "tag_id" smallint NOT NULL
);


ALTER TABLE "public"."blob_tags" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."blobs" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"(),
    "uuid" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "title" "text",
    "url" "text",
    "notes" "text",
    "rating" smallint
);


ALTER TABLE "public"."blobs" OWNER TO "postgres";


ALTER TABLE "public"."blobs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."blobs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."blob_tags"
    ADD CONSTRAINT "blob_tags_pkey" PRIMARY KEY ("blob_id", "tag_id");



ALTER TABLE ONLY "public"."blobs"
    ADD CONSTRAINT "blobs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."blobs"
    ADD CONSTRAINT "blobs_uuid_key" UNIQUE ("uuid");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_name_key" UNIQUE ("name");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



CREATE INDEX "idx_blobs_uuid" ON "public"."blobs" USING "btree" ("uuid");



CREATE OR REPLACE TRIGGER "tsvectorupdate" BEFORE INSERT OR UPDATE ON "public"."tags" FOR EACH ROW EXECUTE FUNCTION "public"."tags_search_vector_update"();



ALTER TABLE ONLY "public"."blob_tags"
    ADD CONSTRAINT "blob_tags_blob_id_fkey" FOREIGN KEY ("blob_id") REFERENCES "public"."blobs"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."blob_tags"
    ADD CONSTRAINT "blob_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON DELETE CASCADE;



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "public"."tags"("id");



CREATE POLICY "Allow me to do everything" ON "public"."blob_tags" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = 'd63b5e2d-722b-46ac-8994-26721e143fb8'::"uuid"));



CREATE POLICY "Allow me to do everything" ON "public"."blobs" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = 'd63b5e2d-722b-46ac-8994-26721e143fb8'::"uuid"));



CREATE POLICY "Allow me to do everything" ON "public"."tags" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = 'd63b5e2d-722b-46ac-8994-26721e143fb8'::"uuid"));



ALTER TABLE "public"."blob_tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."blobs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."get_parent_tags_and_siblings"("tag_ids" bigint[]) TO "anon";
GRANT ALL ON FUNCTION "public"."get_parent_tags_and_siblings"("tag_ids" bigint[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_parent_tags_and_siblings"("tag_ids" bigint[]) TO "service_role";



GRANT ALL ON FUNCTION "public"."get_parent_tags_multiple"("tag_ids" bigint[]) TO "anon";
GRANT ALL ON FUNCTION "public"."get_parent_tags_multiple"("tag_ids" bigint[]) TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_parent_tags_multiple"("tag_ids" bigint[]) TO "service_role";



GRANT ALL ON TABLE "public"."tags" TO "anon";
GRANT ALL ON TABLE "public"."tags" TO "authenticated";
GRANT ALL ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON FUNCTION "public"."search_tags_by_prefix"("prefix" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."search_tags_by_prefix"("prefix" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."search_tags_by_prefix"("prefix" "text") TO "service_role";



GRANT ALL ON FUNCTION "public"."tags_search_vector_update"() TO "anon";
GRANT ALL ON FUNCTION "public"."tags_search_vector_update"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."tags_search_vector_update"() TO "service_role";


















GRANT ALL ON TABLE "public"."blob_tags" TO "anon";
GRANT ALL ON TABLE "public"."blob_tags" TO "authenticated";
GRANT ALL ON TABLE "public"."blob_tags" TO "service_role";



GRANT ALL ON TABLE "public"."blobs" TO "anon";
GRANT ALL ON TABLE "public"."blobs" TO "authenticated";
GRANT ALL ON TABLE "public"."blobs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."blobs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."blobs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."blobs_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
